---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/docker-compose.yaml -o /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/k8s-manifest.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-application
  name: frontend-application
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: frontend-application
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/docker-compose.yaml -o /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/k8s-manifest.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-application
  name: frontend-application
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: frontend-application
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/docker-compose.yaml -o /Users/Dilip_Singh/Documents/k8s-designer/k8s-designer-backend/tmp/1/k8s-manifest.yaml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/1-default: "true"
        io.kompose.service: frontend-application
    spec:
      containers:
        - env:
            - name: BACKEND_API_URL
              value: http://backend-application/8080
            - name: DEBUG
              value: "true"
          image: nginx:latest
          name: frontend-application
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: 1-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/1-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/1-default: "true"

